<a href="https://colab.research.google.com/github/htsnet/estudos-aprendizado-de-maquina/blob/master/Aleatoriedade_Rede_Neural_com_fixacao_de_seed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Como evitar a aleatoriedade na geração de modelo de rede neural

Este notebook mostra como a rede neural trabalha com o conceito de aleatoriedade. A cada execução do notebook haverá uma variação no resultado do modelo e predição.

A lógica do problema é:
- Um arquivo de base contendo 9 elementos como um único atributo, iniciando em 0 e indo até 0.8 (passo 0.1)
- O campo de target com o valor do atributo + 0.1

A predição tem falhas propositais. A modelagem com apenas 100 épocas não tem uma eficiência adequada.

Já na segunda execução, com 1.000 épocas, o resultado passa a ser correto.

Estudo baseado em https://machinelearningmastery.com/reproducible-results-neural-networks-keras/

Este exercício é uma variante do "Aleatoriedade Rede Neural"

Neste exemplo, ao se fornecer um SEED para o processamento, em todas as execuções o resultado será similar.

In [1]:
from pandas import DataFrame
from pandas import concat
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import mean_squared_error
from numpy.random import seed

Using TensorFlow backend.


In [2]:
#define um SEED para o processo
seed(1)

In [3]:
#define função do modelo
def fit_model(X, y):
  # define a rede neural
  model = Sequential()
  model.add(Dense(10, input_dim=1))
  model.add(Dense(1))
  model.compile(loss='mean_squared_error',
                optimizer='adam')
  
  # executa o ajuste ao modelo
  model.fit(X, y, epochs=100, batch_size=len(X), verbose=0)

  #previsão
  forecast = model.predict(X, verbose=0)
  print('Valores previstos:')
  for i in range(0, len(forecast)):
    print('{:.1f}'.format(forecast[i][0]))
  print('Taxa de erro:', mean_squared_error(y, forecast[:,0]))
  print('\n')

In [4]:
#cria uma sequência de números
length = 10
sequence = [i/float(length) for i in range(length)]
print(sequence)

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]


In [5]:
#cria o Dataframe
df = DataFrame(sequence)
df = concat([df.shift(1), df], axis=1)
df.head(15)

0    0
0  NaN  0.0
1  0.0  0.1
2  0.1  0.2
3  0.2  0.3
4  0.3  0.4
5  0.4  0.5
6  0.5  0.6
7  0.6  0.7
8  0.7  0.8
9  0.8  0.9

In [6]:
#remove valores nulos
df.dropna(inplace=True)
df.head(10)

0    0
1  0.0  0.1
2  0.1  0.2
3  0.2  0.3
4  0.3  0.4
5  0.4  0.5
6  0.5  0.6
7  0.6  0.7
8  0.7  0.8
9  0.8  0.9

In [7]:
#converte para um formato mais adequado ao MLP
values = df.values
values

array([[0. , 0.1],
       [0.1, 0.2],
       [0.2, 0.3],
       [0.3, 0.4],
       [0.4, 0.5],
       [0.5, 0.6],
       [0.6, 0.7],
       [0.7, 0.8],
       [0.8, 0.9]])

In [8]:
#separa atributo e target
X, y = values[:,0], values[:,1]
print(X)
print(y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [9]:
#repete o modelo x vezes
repeats = 100
for i in range(repeats):
  print("Execução nº ", i)
  fit_model(X, y)

Execução nº  0
Valores previstos:
0.2
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
Taxa de erro: 0.0012079659592291155


Execução nº  1
Valores previstos:
0.2
0.3
0.4
0.4
0.5
0.6
0.7
0.8
0.8
Taxa de erro: 0.0036601706971978645


Execução nº  2
Valores previstos:
0.2
0.3
0.4
0.5
0.5
0.6
0.7
0.7
0.8
Taxa de erro: 0.007348160382988647


Execução nº  3
Valores previstos:
0.3
0.4
0.4
0.4
0.5
0.5
0.6
0.6
0.6
Taxa de erro: 0.026311866448488454


Execução nº  4
Valores previstos:
0.4
0.4
0.4
0.4
0.4
0.5
0.5
0.5
0.5
Taxa de erro: 0.051506554748236115


Execução nº  5
Valores previstos:
0.3
0.4
0.4
0.4
0.5
0.5
0.6
0.6
0.6
Taxa de erro: 0.027964213318955974


Execução nº  6
Valores previstos:
0.2
0.3
0.3
0.4
0.5
0.6
0.7
0.8
0.9
Taxa de erro: 0.0015550964539520775


Execução nº  7
Valores previstos:
0.2
0.3
0.4
0.4
0.5
0.6
0.7
0.7
0.8
Taxa de erro: 0.0038105193600255116


Execução nº  8
Valores previstos:
0.4
0.4
0.4
0.4
0.4
0.4
0.5
0.5
0.5
Taxa de erro: 0.05875103014218383


Execução nº  9
Valores previstos:
